### ISSUE TITLE
Can you offer other dependence cmake or source?

### ISSUE THREAD

**Issue by GerrieWell** [yifeiwu/RegistrationOptimization#1]
What is vtkmy??Where I can found its *.cmake?
and kdtree is this one ?https://github.com/jtsiomb/kdtree.
Thank you ^_^

**Comment by yifeiwu** [comment]
You can use any kd tree library, I just picked the first one I found from google results. VTKMY is a custom library written for our lab. But for the purposes of this you do not need it.

**Comment by GerrieWell** [comment]
Thank to you answer,I compiled it already.I set two .ply point cloud as inputs .It work fine.  
But Sorry I can't understand your code .Do you hand some tips for me ? 

It seem many variables are meaningless,like `BdryElmReader` never call GetOutput() .Which paper do you refer? And can you  demonstrate your result? It would be helpful if you can release your lastest version.

Thank you very much!

**Comment by yifeiwu** [comment]
Here's my thesis http://etd.library.vanderbilt.edu/available/etd-03272014-152811/. The code is a small part of the work. Don't worry if you don't understand all of it. A lot of the code is remnants from a larger framework. For example the original purpose was to align a pointcloud to a finite element model which explains why there's a boundary element reader....which doesn't really exist in this project. I haven't had the chance to clean the code up too much. Sorry. 

What is the goal of your project?

**Comment by GerrieWell** [comment]
We just want to rigid align mutli point clouds then mix them into one point cloud .I will figure it out . Thank .You can close this issue.  
ps : I just notice your name .Are you Chinese ? 哈哈.祝幸福安康.^_^.

**Comment by yifeiwu** [comment]
I am, but I can't read chinese sorry. If you are registering rigidly, this would suit you better. 

https://github.com/yifeiwu/PCLRigidFeatureRegistration

This one is based on the point cloud library framework. The code you're using now is more for nonrigid registrations.
